### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by EmmanVazz** [Julien-Mialon/Storm.ImageResizeTask#1]
It would be nice to have some doc to see how to use this. Currently looking through the code to try to figure it out. Thanks .

**Comment by EmmanVazz** [comment]
I figured it out. Good job on this, really smart implementation.

Some quick step to get started that might be useful in the readme:

1) install nuget in droid project
2) add ```<UsingTask AssemblyFile="..\..\packages\Storm.ImageResizeTask.0.1.0\resize\Storm.ImageResizeTask.Android.dll" TaskName="Storm.ImageResizeTask.Android.AndroidResizeTask" />``` in your droid .csproj


Example usage in .csproj, ImagePath is the path inside one of the drawable folders (Look at note for explanation of why that is): 
```
<AndroidResizeTask InputImages="@(ImagePath)">
      <Output TaskParameter="OutputImages" ItemName="OutputResourceImages" />
    </AndroidResizeTask>
    <Message Importance="high" Text="Add images to resource @(OutputResourceImages)" />
```

Note: This task can detect the size of the image based on the drawable folder name. It is recommended that you give the task the highest resolution (192x192) in the drawable-xxxhdpi folder, as downscaling produced better results than upscaling. The task will scale the image based on the [android specifications ](https://developer.android.com/guide/practices/screens_support.html) and place the scaled images in their proper files.

**Comment by Julien-Mialon** [comment]
Hello @EmmanVazz 

Thank you for this, I will add some documentation on the Readme. Just a quick question, does your step 2 is mandatory ? It should have been added automatically when you install the nuget. (At least on my tries, it works without issue)

Thanks.

**Comment by EmmanVazz** [comment]
Seems like you are right. I think I was copying one the files where I saw the task being used and thought it was necessary.
